bundler_args: ""
script:
#   - cd profile-repo
#   - sed -i 's/{% asset_path/{% asset/g' _includes/head.html
#   - echo -e "exclude:\n- Gemfile\n- Gemfile.lock\n- node_modules\n- vendor/bundle/\n- vendor/cache/\n- vendor/gems/\n- vendor/ruby/\n- autoprefixer.yml\n- README.md\n- LICENSE.md\n- tags/*.md\n- Rakefile" >> _config_custom.yml
#   - bundle exec jekyll build --profile --config _config.yml,_config_custom.yml
  - travis_wait bundle exec ruby script/profile-repo Renderer
#   - rbspy record ruby script/rbspy-jbuild
#   - script/stackprof
#   - bundle exec stackprof stackprof-cpu.dump --method 'Jekyll::Document#related_posts'
#   - bundle exec jekyll build --source docs

cache: bundler
language: ruby
sudo: false

rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9

# env:
#   matrix:
#     - RBSPY_VERSION=0.2.2

# before_script:
#   - script/install-rbspy $RBSPY_VERSION
#   - PATH=$PATH:$PWD
#   - PATH=$PATH:$PWD/rbspy-$RBSPY_VERSION/bin

before_install:
  - gem update --system
  - git clone --depth=50 --branch=travis-benchmarks https://github.com/DirtyF/nicolas-hoizey.com.git profile-repo
  - echo -e "\n gem 'method_profiler'" >> $PWD/profile-repo/Gemfile
  - BUNDLE_GEMFILE=$PWD/profile-repo/Gemfile

install:
  bundle install --path /home/travis/build/ashmaroli/jekyll/vendor/bundle

# deploy:
#   provider: pages
#   github-token: $GITHUB_TOKEN
#   local-dir: "./rbspy"
#   skip-cleanup: true
#   keep-history: true
#   target-branch: rbspy-report
#   verbose: true
#   on:
#     branch: master
