bundler_args: --without benchmark:development
script: bundle exec jekyll build --source docs
cache: bundler
language: ruby
sudo: false

rvm:
  - &ruby1 2.6.0-preview1
  - &ruby2 2.5.0
  - &ruby3 2.4.3
  - &ruby4 2.3.6
  - &ruby5 2.2.9
  - &jruby jruby-9.1.15.0

matrix:
  include:
    - rvm: *ruby1
      env: ROUGE_VERSION=1.11.1 # runs everything with this version

after_success:
  - bundle exec jekyll build --source docs --verbose

before_install:
  - gem update --system
