bundler_args: --without benchmark:site:development
script: script/cibuild
cache: bundler
language: ruby
sudo: false

rvm:
  - &ruby1 2.4.2
  - &ruby2 2.3.5
  - &ruby3 2.2.8

env:
  matrix:
    - TEST_SUITE=rubyprof
    - TEST_SUITE=stackprof

before_install:
  - gem update --system 2.6.14
