script:
  - script/stackprof
  - bundle exec stackprof stackprof-cpu.dump --method 'Jekyll::Drops::Drop#\[\]'
cache: bundler
language: ruby
sudo: false

rvm:
  - &ruby1 2.5.0
  - &ruby2 2.4.3
  - &ruby3 2.3.6
  - &ruby4 2.2.9

env:
  matrix:
    - TEST_SUITE=fmt

before_install:
  - gem update --system
